name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: macos-latest-xlarge

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21.4

    - name: Build binary
      run: go build -o kegwasher-darwin-arm64 github.com/szEvEz/kegwasher/cmd/kegwasher

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: kegwasher-darwin-arm64
